--- #YAML:1.0
name:               Digest-ssdeep
version:            0.9.0
abstract:           Pure Perl ssdeep (CTPH) fuzzy hashing
author:
    - Reinoso Guzman <reinoso.guzman@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:           0
    Text::WagnerFischer:  0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
