---
abstract: 'Pure Perl ssdeep (CTPH) fuzzy hashing'
author:
  - 'Reinoso Guzman <reinoso.guzman@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Digest-ssdeep
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  Text::WagnerFischer: 0
  version: 0
version: v0.9.3
